In [1]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df =pd.read_csv('christopher.csv', header=None)[[3,4,5,7]]

In [3]:
df[7] = df[7].astype(int)

In [4]:
X = df[[3,4,5]].to_numpy()
y = df[7].to_numpy()

In [5]:
logistic_model = LogisticRegression(random_state=0).fit(X, y)

In [6]:
table = []
for i in range(1,13):
    for j in range(1, 13):
        table.append([i,j,i*j])


In [18]:
result_prediction = logistic_model.predict_proba(np.array(table))

In [19]:
result_prediction

array([[0.01082334, 0.98917666],
       [0.01302833, 0.98697167],
       [0.01567542, 0.98432458],
       [0.01885006, 0.98114994],
       [0.02265286, 0.97734714],
       [0.02720155, 0.97279845],
       [0.03263313, 0.96736687],
       [0.03910568, 0.96089432],
       [0.04679991, 0.95320009],
       [0.05591991, 0.94408009],
       [0.06669279, 0.93330721],
       [0.07936659, 0.92063341],
       [0.01125332, 0.98874668],
       [0.01346508, 0.98653492],
       [0.01610446, 0.98389554],
       [0.01925111, 0.98074889],
       [0.0229982 , 0.9770018 ],
       [0.02745423, 0.97254577],
       [0.0327447 , 0.9672553 ],
       [0.03901375, 0.96098625],
       [0.04642543, 0.95357457],
       [0.05516431, 0.94483569],
       [0.06543528, 0.93456472],
       [0.07746181, 0.92253819],
       [0.01170019, 0.98829981],
       [0.01391626, 0.98608374],
       [0.01654505, 0.98345495],
       [0.01966051, 0.98033949],
       [0.02334868, 0.97665132],
       [0.02770918, 0.97229082],
       [0.

In [57]:
df = pd.read_csv('christopher.csv', header=None)[[3,4,5,6]]

In [58]:
df

3   4    5         6
0     7   7   49  2.643975
1     7  11   77  1.304327
2     4   2    8  1.259946
3    11   5   55  1.518821
4    10  11  110  1.597719
..   ..  ..  ...       ...
722   1   1    1  0.866332
723   4   4   16  2.441307
724   8   4   32  2.879969
725   5  10   50  2.925051
726   5  10   50  2.058603

[727 rows x 4 columns]

In [59]:
X = df[[3,4,5]].to_numpy()
y = df[6].to_numpy()

In [60]:
X

array([[ 7,  7, 49],
       [ 7, 11, 77],
       [ 4,  2,  8],
       ...,
       [ 8,  4, 32],
       [ 5, 10, 50],
       [ 5, 10, 50]])

In [62]:
linear_model = LinearRegression().fit(X, y)

In [63]:
linear_model.score(X, y)

0.06029104244466799

In [64]:
linear_model.coef_

array([ 0.09489419,  0.07962498, -0.00699762])

In [65]:
linear_model.intercept_

1.0913645477452747

In [66]:
time_prediction = linear_model.predict(np.array(table))

In [67]:
time_prediction

array([1.25888609, 1.33151345, 1.4041408 , 1.47676816, 1.54939551,
       1.62202287, 1.69465022, 1.76727758, 1.83990493, 1.91253229,
       1.98515964, 2.057787  , 1.34678266, 1.41241239, 1.47804212,
       1.54367185, 1.60930159, 1.67493132, 1.74056105, 1.80619078,
       1.87182051, 1.93745024, 2.00307998, 2.06870971, 1.43467922,
       1.49331133, 1.55194344, 1.61057555, 1.66920766, 1.72783977,
       1.78647188, 1.84510399, 1.90373609, 1.9623682 , 2.02100031,
       2.07963242, 1.52257579, 1.57421028, 1.62584476, 1.67747925,
       1.72911373, 1.78074822, 1.8323827 , 1.88401719, 1.93565168,
       1.98728616, 2.03892065, 2.09055513, 1.61047236, 1.65510922,
       1.69974608, 1.74438294, 1.78901981, 1.83365667, 1.87829353,
       1.92293039, 1.96756726, 2.01220412, 2.05684098, 2.10147784,
       1.69836892, 1.73600816, 1.7736474 , 1.81128664, 1.84892588,
       1.88656512, 1.92420436, 1.9618436 , 1.99948284, 2.03712208,
       2.07476132, 2.11240056, 1.78626549, 1.8169071 , 1.84754

In [121]:
pt = pd.DataFrame(data=table, columns=["m1", "m2","product"])

In [122]:
pt['predict_result'] = result_prediction
pt['predict_time'] = time_prediction

## Performance Table

In [145]:
pt

m1  m2  product  predict_result  predict_time    key
0     1   1        1               1      1.258886    1X1
1     1   2        2               1      1.331513    1X2
2     1   3        3               1      1.404141    1X3
3     1   4        4               1      1.476768    1X4
4     1   5        5               1      1.549396    1X5
5     1   6        6               1      1.622023    1X6
6     1   7        7               1      1.694650    1X7
7     1   8        8               1      1.767278    1X8
8     1   9        9               1      1.839905    1X9
9     1  10       10               1      1.912532   1X10
10    1  11       11               1      1.985160   1X11
11    1  12       12               1      2.057787   1X12
12    2   1        2               1      1.346783    2X1
13    2   2        4               1      1.412412    2X2
14    2   3        6               1      1.478042    2X3
15    2   4        8               1      1.543672    2X4
16    2   5       10               1      1.609302    2X5
17    2   6       12               1      1.674931    2X6
18    2   7       14               1      1.740561    2X7
19    2   8       16               1      1.806191    2X8
20    2   9       18               1      1.871821    2X9
21    2  10       20               1      1.937450   2X10
22    2  11       22               1      2.003080   2X11
23    2  12       24               1      2.068710   2X12
24    3   1        3               1      1.434679    3X1
25    3   2        6               1      1.493311    3X2
26    3   3        9               1      1.551943    3X3
27    3   4       12               1      1.610576    3X4
28    3   5       15               1      1.669208    3X5
29    3   6       18               1      1.727840    3X6
30    3   7       21               1      1.786472    3X7
31    3   8       24               1      1.845104    3X8
32    3   9       27               1      1.903736    3X9
33    3  10       30               1      1.962368   3X10
34    3  11       33               1      2.021000   3X11
35    3  12       36               1      2.079632   3X12
36    4   1        4               1      1.522576    4X1
37    4   2        8               1      1.574210    4X2
38    4   3       12               1      1.625845    4X3
39    4   4       16               1      1.677479    4X4
40    4   5       20               1      1.729114    4X5
41    4   6       24               1      1.780748    4X6
42    4   7       28               1      1.832383    4X7
43    4   8       32               1      1.884017    4X8
44    4   9       36               1      1.935652    4X9
45    4  10       40               1      1.987286   4X10
46    4  11       44               1      2.038921   4X11
47    4  12       48               1      2.090555   4X12
48    5   1        5               1      1.610472    5X1
49    5   2       10               1      1.655109    5X2
50    5   3       15               1      1.699746    5X3
51    5   4       20               1      1.744383    5X4
52    5   5       25               1      1.789020    5X5
53    5   6       30               1      1.833657    5X6
54    5   7       35               1      1.878294    5X7
55    5   8       40               1      1.922930    5X8
56    5   9       45               1      1.967567    5X9
57    5  10       50               1      2.012204   5X10
58    5  11       55               1      2.056841   5X11
59    5  12       60               1      2.101478   5X12
60    6   1        6               1      1.698369    6X1
61    6   2       12               1      1.736008    6X2
62    6   3       18               1      1.773647    6X3
63    6   4       24               1      1.811287    6X4
64    6   5       30               1      1.848926    6X5
65    6   6       36               1      1.886565    6X6
66    6   7       42               1      1.924204    6X7
67    6   8       48               1      1.961844    6X8
68 

In [79]:
df =  pd.read_csv('christopher.csv', header=None)

In [124]:
df['key'] = df[3].astype(str)+'X'+ df[4].astype(str)
pt['key'] = pt['m1'].astype(str)+'X'+pt['m2'].astype(str)

In [125]:
pt

m1  m2  product  predict_result  predict_time    key
0     1   1        1               1      1.258886    1X1
1     1   2        2               1      1.331513    1X2
2     1   3        3               1      1.404141    1X3
3     1   4        4               1      1.476768    1X4
4     1   5        5               1      1.549396    1X5
5     1   6        6               1      1.622023    1X6
6     1   7        7               1      1.694650    1X7
7     1   8        8               1      1.767278    1X8
8     1   9        9               1      1.839905    1X9
9     1  10       10               1      1.912532   1X10
10    1  11       11               1      1.985160   1X11
11    1  12       12               1      2.057787   1X12
12    2   1        2               1      1.346783    2X1
13    2   2        4               1      1.412412    2X2
14    2   3        6               1      1.478042    2X3
15    2   4        8               1      1.543672    2X4
16    2   5       10               1      1.609302    2X5
17    2   6       12               1      1.674931    2X6
18    2   7       14               1      1.740561    2X7
19    2   8       16               1      1.806191    2X8
20    2   9       18               1      1.871821    2X9
21    2  10       20               1      1.937450   2X10
22    2  11       22               1      2.003080   2X11
23    2  12       24               1      2.068710   2X12
24    3   1        3               1      1.434679    3X1
25    3   2        6               1      1.493311    3X2
26    3   3        9               1      1.551943    3X3
27    3   4       12               1      1.610576    3X4
28    3   5       15               1      1.669208    3X5
29    3   6       18               1      1.727840    3X6
30    3   7       21               1      1.786472    3X7
31    3   8       24               1      1.845104    3X8
32    3   9       27               1      1.903736    3X9
33    3  10       30               1      1.962368   3X10
34    3  11       33               1      2.021000   3X11
35    3  12       36               1      2.079632   3X12
36    4   1        4               1      1.522576    4X1
37    4   2        8               1      1.574210    4X2
38    4   3       12               1      1.625845    4X3
39    4   4       16               1      1.677479    4X4
40    4   5       20               1      1.729114    4X5
41    4   6       24               1      1.780748    4X6
42    4   7       28               1      1.832383    4X7
43    4   8       32               1      1.884017    4X8
44    4   9       36               1      1.935652    4X9
45    4  10       40               1      1.987286   4X10
46    4  11       44               1      2.038921   4X11
47    4  12       48               1      2.090555   4X12
48    5   1        5               1      1.610472    5X1
49    5   2       10               1      1.655109    5X2
50    5   3       15               1      1.699746    5X3
51    5   4       20               1      1.744383    5X4
52    5   5       25               1      1.789020    5X5
53    5   6       30               1      1.833657    5X6
54    5   7       35               1      1.878294    5X7
55    5   8       40               1      1.922930    5X8
56    5   9       45               1      1.967567    5X9
57    5  10       50               1      2.012204   5X10
58    5  11       55               1      2.056841   5X11
59    5  12       60               1      2.101478   5X12
60    6   1        6               1      1.698369    6X1
61    6   2       12               1      1.736008    6X2
62    6   3       18               1      1.773647    6X3
63    6   4       24               1      1.811287    6X4
64    6   5       30               1      1.848926    6X5
65    6   6       36               1      1.886565    6X6
66    6   7       42               1      1.924204    6X7
67    6   8       48               1      1.961844    6X8
68 

In [129]:
pd.set_option('display.max_rows', None)
mdf = pd.merge(df, pt, how='left', left_on='key', right_on='key')

In [127]:
combined_df

0            1                               2   3   4    5  \
0    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:52 +0000   7   7   49   
1    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:53 +0000   7  11   77   
2    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:54 +0000   4   2    8   
3    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:56 +0000  11   5   55   
4    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:58 +0000  10  11  110   
5    1.612489e+09  Christopher  Fri 05 Feb 2021 01:33:59 +0000  11   8   88   
6    1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:01 +0000   7   5   35   
7    1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:03 +0000   2   6   12   
8    1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:05 +0000   1   8    8   
9    1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:06 +0000   1   9    9   
10   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:08 +0000   2   3    6   
11   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:10 +0000   2  10   20   
12   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:14 +0000   7   6   42   
13   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:15 +0000   9  11   99   
14   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:18 +0000   7   8   56   
15   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:20 +0000   7  10   70   
16   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:22 +0000   3   9   27   
17   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:24 +0000  10   8   80   
18   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:25 +0000   5   1    5   
19   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:28 +0000   7   9   63   
20   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:37 +0000  12  11  132   
21   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:47 +0000   8   6   48   
22   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:50 +0000  11  11  121   
23   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:52 +0000   7  12   84   
24   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:56 +0000   3  12   36   
25   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:57 +0000   8  11   88   
26   1.612489e+09  Christopher  Fri 05 Feb 2021 01:34:58 +0000   5   1    5   
27   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:00 +0000  10   9   90   
28   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:01 +0000   5  11   55   
29   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:02 +0000   3  11   33   
30   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:04 +0000  11   7   77   
31   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:06 +0000   7  12   84   
32   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:09 +0000   9  12  108   
33   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:12 +0000   4   9   36   
34   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:14 +0000  10  10  100   
35   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:16 +0000   1   7    7   
36   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:18 +0000   9   6   54   
37   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:20 +0000   3   5   15   
38   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:23 +0000   6  12   72   
39   1.612489e+09  Christopher  Fri 05 Feb 2021 01:35:24 +0000   8   9   72   
40   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:20 +0000   5   1    5   
41   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:22 +0000   7  12   84   
42   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:25 +0000   8   3   24   
43   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:27 +0000   7   5   35   
44   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:28 +0000   6   2   12   
45   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:30 +0000   9   6   54   
46   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:32 +0000   3   9   27   
47   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:34 +0000  12   2   24   
48   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:36 +0000   5  10   50   
49   1.612490e+09  christopher  Fri 05 Feb 2021 01:46:37 +0000   5

In [143]:
mdf[mdf['product']==144][[2, 'key','product',6,'predict_time','predict_result']]

2    key  product         6  predict_time  \
82   Fri 05 Feb 2021 01:48:12 +0000  12X12      144  3.161257      2.177937   
187  Fri 05 Feb 2021 02:04:33 +0000  12X12      144  3.903917      2.177937   
637  Fri 05 Feb 2021 02:11:51 +0000  12X12      144  1.968084      2.177937   
646  Fri 05 Feb 2021 02:12:07 +0000  12X12      144  1.720844      2.177937   
657  Fri 05 Feb 2021 02:11:51 +0000  12X12      144  1.968084      2.177937   
666  Fri 05 Feb 2021 02:12:07 +0000  12X12      144  1.720844      2.177937   
684  Fri 05 Feb 2021 02:11:51 +0000  12X12      144  1.968084      2.177937   
693  Fri 05 Feb 2021 02:12:07 +0000  12X12      144  1.720844      2.177937   

     predict_result  
82                1  
187               1  
637               1  
646               1  
657               1  
666               1  
684               1  
693               1